### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by holly-johnson** [dh609007/harnly-portfolio-site#1]
Your header should only contain items that are in your header on every page. So remove the hero section out of there. 

Add grid-x around the cells - it's breaking your whole homepage on mobile.

<img width="1429" alt="Screen Shot 2020-04-30 at 11 23 13 PM" src="https://user-images.githubusercontent.com/15253544/80781881-a708f400-8b39-11ea-9fd9-e2379c3b7739.png">
<img width="1375" alt="Screen Shot 2020-04-30 at 11 23 22 PM" src="https://user-images.githubusercontent.com/15253544/80781883-a96b4e00-8b39-11ea-99cc-3a2f19eddbfd.png">

**Comment by dh609007** [comment]
fixed this too.

**Comment by dh609007** [comment]
i think.
