### ISSUE TITLE
Tablet: Hero size

### ISSUE THREAD

**Issue by holly-johnson** [dh609007/harnly-portfolio-site#11]
At tablet, the hero seems out of proportion to the work thumbnails. You have a nice hierarchy at desktop when the thumbnails are a bit larger - attempt to get that same feeling.  

<img width="517" alt="Screen Shot 2020-05-08 at 9 09 56 PM" src="https://user-images.githubusercontent.com/15253544/81461340-a0e5c980-9170-11ea-9681-3159fdfe1a9c.png">

**Comment by dh609007** [comment]
left alone.  couldn't fix in time.
