### ISSUE TITLE
Mobile: Hero Line-height

### ISSUE THREAD

**Issue by holly-johnson** [dh609007/harnly-portfolio-site#12]
I would tighten up the line-height on mobile (see top pic)

<img width="544" alt="Screen Shot 2020-05-08 at 9 19 13 PM" src="https://user-images.githubusercontent.com/15253544/81461469-ac85c000-9171-11ea-848d-3f4b6290203b.png">

<img width="508" alt="Screen Shot 2020-05-08 at 9 09 02 PM" src="https://user-images.githubusercontent.com/15253544/81461394-0b970500-9171-11ea-9255-cb099cc11714.png">

**Comment by dh609007** [comment]
fixed
