### ISSUE TITLE
Mobile: Hero height

### ISSUE THREAD

**Issue by holly-johnson** [dh609007/harnly-portfolio-site#13]
(after tightening your line height). I don't think either way is right or wrong depending on intention but I want you to be sure to consider it. On your mobile you don't see the next section or you do (the white at the bottom).

<img width="425" alt="Screen Shot 2020-05-08 at 9 27 44 PM" src="https://user-images.githubusercontent.com/15253544/81461645-ca9ff000-9172-11ea-81ab-f8ac279040a3.png">

<img width="544" alt="Screen Shot 2020-05-08 at 9 19 13 PM" src="https://user-images.githubusercontent.com/15253544/81461564-68df8600-9172-11ea-9556-bc79331e3115.png">

**Comment by dh609007** [comment]
fixed.
