### ISSUE TITLE
Type color

### ISSUE THREAD

**Issue by holly-johnson** [dh609007/harnly-portfolio-site#14]
It appears you aren't using #333 for your p tags. This will also help in your mobile rag being so harsh that i've shown here as well as the color.

<img width="490" alt="Screen Shot 2020-05-08 at 9 40 15 PM" src="https://user-images.githubusercontent.com/15253544/81461899-87df1780-9174-11ea-8a17-423962e63129.png">

**Comment by dh609007** [comment]
fixed.
