### ISSUE TITLE
Mobile: Center Copy cell

### ISSUE THREAD

**Issue by holly-johnson** [dh609007/harnly-portfolio-site#15]
It looks like to add the extra padding you wanted - you did 95% of the width. Make sure you add a margin: 0 auto; here to center that cell. The rag looks even more harsh because of it. Here's you can see it feels better (also has #333 for color)

<img width="490" alt="Screen Shot 2020-05-08 at 9 40 15 PM" src="https://user-images.githubusercontent.com/15253544/81461937-cd9be000-9174-11ea-9d8f-baf78ded1f1b.png">

**Comment by dh609007** [comment]
fixed.
