### ISSUE TITLE
Copyright position/alignment

### ISSUE THREAD

**Issue by holly-johnson** [dh609007/harnly-portfolio-site#2]
It almost feels broken with your copyright hanging out all by itself. :(. Maybe it's not alignment but rather size possibly? 

<img width="1440" alt="Screen Shot 2020-04-30 at 11 25 39 PM" src="https://user-images.githubusercontent.com/15253544/80782099-66f64100-8b3a-11ea-9e4d-d978fcc54f28.png">

**Comment by holly-johnson** [comment]
Feels really strange on mobile.

<img width="604" alt="Screen Shot 2020-04-30 at 11 34 11 PM" src="https://user-images.githubusercontent.com/15253544/80782388-99ed0480-8b3b-11ea-9546-8470177b9827.png">

**Comment by dh609007** [comment]
fixed.
