### ISSUE TITLE
Spacing on mobile

### ISSUE THREAD

**Issue by holly-johnson** [dh609007/harnly-portfolio-site#6]
The space on mobile seems excessive

<img width="438" alt="Screen Shot 2020-04-30 at 11 33 32 PM" src="https://user-images.githubusercontent.com/15253544/80782290-23e89d80-8b3b-11ea-9a0a-33aced0fa15d.png">

**Comment by dh609007** [comment]
i actually mentioned this in my browser testing.  fixed it!
