### ISSUE TITLE
Work type alignment

### ISSUE THREAD

**Issue by holly-johnson** [dh609007/harnly-portfolio-site#7]
The alignment on mobile feels rocky. Between the rag (which you won't be able to control) and the center aligned headings - it feels ungrounded and hard to read.

<img width="464" alt="Screen Shot 2020-04-30 at 11 33 37 PM" src="https://user-images.githubusercontent.com/15253544/80782320-3ebb1200-8b3b-11ea-9f6a-ecd0db4f6f39.png">

**Comment by dh609007** [comment]
i'll ask everyone about this in crit.
